apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: stock-pod-info
    namespace: staging
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: instance
        alb.ingress.kubernetes.io/tags: Environment=staging,Team=stocks-project
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stocks-app
                port:
                  number: 80
          - path: /stock_result
            pathType: Prefix
            backend:
              service:
                name: stocks-app
                port:
                  number: 80