---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: stock-cluster
  region: {env.AWS_REGION}
  tags:
    project: stocks-project

nodeGroups:
  - name: worker-node
    instanceType: m5.large
    desiredCapacity: 3
  
