---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-app
  namespace: staging
  labels:
    app: stocks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stocks-app
  template:
    metadata:
      labels:
        app: stocks-app
    spec:
      containers:
      - name: stocks-app
        image: docker.io/ccrawford6/stocks-info:latest
        ports:
        - containerPort: 80
